# Generated by Django 3.2.25 on 2024-04-27 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240423_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Range',
        ),
        migrations.AlterModelOptions(
            name='range',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.range'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Toner', max_length=254),
            preserve_default=False,
        ),
    ]
